"""Builder validation pipeline, pre/post step hooks, and auto-fix orchestration."""

import hashlib
import os
import re
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from planning.project_context import scan_project, build_file_map
from utils.error_diagnosis import diagnose_test_error
from utils.git_integration import auto_commit
from planning.builder_models import FixAttempt, FileSnapshot
from planning.builder_deps import (
    _is_missing_dependency_error, _try_reinstall_deps,
    _validate_dependencies, run_cmd, detect_project_type,
)
from planning.builder_llm import auto_fix

try:
    from tools.testing import tool_run_tests as _test_tool
except ImportError:
    _test_tool = None
try:
    from tools.lint import tool_lint as _lint_tool
except ImportError:
    _lint_tool = None
try:
    from tools.lint import tool_format_code as _format_tool
except ImportError:
    _format_tool = None
try:
    from tools.json_tools import tool_json_validate as _json_validate_tool
except ImportError:
    _json_validate_tool = None
try:
    from tools.dotenv import tool_dotenv_init as _dotenv_init_tool
except ImportError:
    _dotenv_init_tool = None

console = Console()

MAX_FIX_ATTEMPTS = 5


def handle_validation_failure(stage_name: str) -> bool:
    console.print(
        f"\n[bold red]❌ {stage_name} still failing "
        f"after {MAX_FIX_ATTEMPTS} attempts.[/bold red]"
    )
    try:
        action = console.input(
            "[bold](c)ontinue / (q)uit build: [/bold]"
        ).strip().lower()
    except (KeyboardInterrupt, EOFError):
        action = "q"
    return action in ("c", "continue")


def ask_continue() -> bool:
    try:
        action = console.input(
            "[bold](r)etry / (c)ontinue / (q)uit: [/bold]"
        ).strip().lower()
    except (KeyboardInterrupt, EOFError):
        action = "q"
    return action not in ("q", "quit")


# ── Post-Step Hooks ───────────────────────────────────────────

def _post_step_hooks(
    base_dir: Path, step: dict, created_files: dict[str, str],
) -> list[str]:
    """Run lightweight checks on files generated by a build step.

    Returns a list of warning/info messages (empty = all good).
    """
    messages: list[str] = []
    step_files = step.get("files_to_create", [])

    # 1. JSON validation for config files
    json_configs = [
        f for f in step_files
        if f.endswith(".json") and (base_dir / f).exists()
    ]
    if json_configs and _json_validate_tool:
        for jf in json_configs:
            try:
                result = _json_validate_tool(str(base_dir / jf))
                if not _parse_tool_result(result):
                    messages.append(
                        f"JSON issue in {jf}: "
                        f"{result.split(chr(10))[0]}"
                    )
            except Exception:
                pass

    # 2. Dotenv init — bootstrap .env from .env.example
    env_templates = (".env.example", ".env.sample", ".env.template")
    created_env_template = any(f in step_files for f in env_templates)
    env_exists = (base_dir / ".env").exists()
    if created_env_template and not env_exists and _dotenv_init_tool:
        original_dir = os.getcwd()
        try:
            os.chdir(str(base_dir))
            result = _dotenv_init_tool("")
            messages.append(result.split("\n")[0])
        except Exception:
            pass
        finally:
            os.chdir(original_dir)

    # 3. Docker compose YAML check
    compose_files = [
        f for f in step_files
        if "docker-compose" in f
        and f.endswith((".yml", ".yaml"))
        and (base_dir / f).exists()
    ]
    for cf in compose_files:
        try:
            import yaml
            yaml.safe_load(
                (base_dir / cf).read_text(encoding="utf-8")
            )
        except Exception as e:
            messages.append(f"YAML issue in {cf}: {e}")

    return messages


# ── Post-Build Cleanup ────────────────────────────────────────

def _post_build_cleanup(
    base_dir: Path, project_info: dict, config: dict,
) -> bool:
    """Run optional cosmetic cleanup after all build steps pass.

    Formats code and runs lint informational pass.
    Gated by config["post_build_cleanup"] (default True).

    Returns True if any formatting changes were made.
    """
    if not config.get("post_build_cleanup", True):
        return False

    changed = False
    console.print("\n[bold]🧹 Post-build cleanup[/bold]")

    # Auto-format (black / prettier / rustfmt / gofmt)
    if _format_tool:
        original_dir = os.getcwd()
        try:
            os.chdir(str(base_dir))
            result = _format_tool(".")
            first_line = result.strip().split("\n")[0]
            console.print(f"  [dim]Format: {first_line}[/dim]")
            if "reformatted" in result.lower() or "changed" in result.lower():
                changed = True
        except Exception as e:
            console.print(
                f"  [yellow]⚠ Format skipped: {e}[/yellow]"
            )
        finally:
            os.chdir(original_dir)

    # Informational lint pass (show top issues, don't block)
    if _lint_tool:
        original_dir = os.getcwd()
        try:
            os.chdir(str(base_dir))
            result = _lint_tool(".")
            lines = result.strip().split("\n")
            first_line = lines[0]
            if _parse_tool_result(result):
                console.print(
                    f"  [dim]Lint: {first_line}[/dim]"
                )
            else:
                console.print(
                    f"  [yellow]Lint: {first_line}[/yellow]"
                )
                for line in lines[1:6]:
                    console.print(f"    [dim]{line}[/dim]")
        except Exception as e:
            console.print(
                f"  [yellow]⚠ Lint skipped: {e}[/yellow]"
            )
        finally:
            os.chdir(original_dir)

    # Auto-commit formatting changes separately
    if changed:
        try:
            auto_commit(
                str(base_dir), "Auto-format code (post-build cleanup)"
            )
            console.print(
                "  [green]✓ Formatting committed[/green]"
            )
        except Exception:
            pass

    return changed


# ── Tool-Based Validation Helpers ─────────────────────────────

def _parse_tool_result(result_text: str) -> bool:
    """Check if a tool result string indicates success.

    Looks at the first line for keywords like "passed", "clean",
    "valid", or "PASSED" to determine pass/fail.
    """
    if not result_text:
        return False
    first_line = result_text.strip().split("\n")[0].lower()
    return any(kw in first_line for kw in ("passed", "clean", "valid"))


def _validate_tool_func(
    tool_func, tool_args: str, base_dir: Path,
    plan: dict, created_files: dict[str, str], config: dict,
    stage_name: str, attempt: int,
    fix_history: list[FixAttempt] | None = None,
) -> bool:
    """Run a tool-function-based validation stage with auto-fix."""
    original_dir = os.getcwd()
    try:
        os.chdir(str(base_dir))
        result_text = tool_func(tool_args)
    except Exception as e:
        console.print(
            f"  [yellow]⚠ {stage_name} tool error: {e}[/yellow]"
        )
        return True  # Don't block on tool errors
    finally:
        os.chdir(original_dir)

    passed = _parse_tool_result(result_text)

    if passed:
        console.print(f"  [green]✓ {stage_name} passed[/green]")
        # Show last few lines of output
        lines = result_text.strip().split("\n")
        for line in lines[-3:]:
            console.print(f"  [dim]{line}[/dim]")
        return True

    console.print(f"  [red]✗ {stage_name} failed[/red]")
    console.print(
        Panel(result_text[:1500], title="Error", border_style="red")
    )

    if attempt < MAX_FIX_ATTEMPTS - 1:
        console.print(
            f"\n[yellow]🔧 Auto-fix attempt "
            f"{attempt + 1}/{MAX_FIX_ATTEMPTS}...[/yellow]"
        )
        error_info = {
            "command": f"{stage_name} (tool)",
            "returncode": 1,
            "stdout": result_text,
            "stderr": "",
        }
        try:
            created_files.update(
                build_file_map(scan_project(base_dir, auto_detect=False))
            )
        except Exception:
            pass

        snapshot = FileSnapshot()
        all_project_files = list(created_files.keys())
        snapshot.snapshot_files(all_project_files[:50], base_dir)

        fixed = auto_fix(
            error_info, base_dir, plan, created_files,
            config, attempt=attempt,
            fix_history=fix_history,
        )

        if fix_history is not None:
            modified = snapshot.get_modified_files()
            fix_history.append(FixAttempt(
                attempt=attempt + 1,
                error_summary=result_text[:300],
                files_modified=modified,
                approach=f"auto_fix attempt {attempt + 1}",
                result="applied" if fixed else "no_change",
            ))

        if not fixed:
            snapshot.rollback()
            console.print("[red]No fixes generated.[/red]")
            if not ask_continue():
                return False

    return False


# ── Validation Pipeline ────────────────────────────────────────

def run_validation_pipeline(
    base_dir, plan, project_info, created_files, config,
    step_label="",
) -> bool:
    # Read optional validation config from plan
    validation_config = plan.get("validation", {})
    skip_stages = set(
        s.lower() for s in validation_config.get("skip_stages", [])
    )
    custom_stages = validation_config.get("custom_stages", [])

    stages = []

    if "xref" not in skip_stages and "cross-reference check" not in skip_stages:
        stages.append(("Cross-Reference Check", "xref", None))
    if "syntax" not in skip_stages and "syntax check" not in skip_stages:
        stages.append(("Syntax Check", "syntax_check", None))

    dep_files = (
        "requirements.txt", "package.json",
        "Cargo.toml", "go.mod",
    )
    has_deps = any(
        (base_dir / f).exists() for f in dep_files
    )

    # Dependency validation before install
    if "deps" not in skip_stages and "dependency check" not in skip_stages and has_deps:
        proj_type = project_info.get("type", "unknown")
        if proj_type in ("python", "node"):
            stages.append(("Dependency Check", "dep_validate", proj_type))

    if "install" not in skip_stages and has_deps:
        install_cmds = project_info.get("install_cmd")
        if install_cmds:
            if isinstance(install_cmds, str):
                install_cmds = [install_cmds]
            labels = ["Create Virtualenv", "Install Dependencies"]
            for i, cmd in enumerate(install_cmds):
                label = labels[i] if i < len(labels) else f"Install Step {i+1}"
                stages.append((label, "command", cmd))

    if "build" not in skip_stages and project_info.get("build_cmd"):
        stages.append((
            "Build", "command", project_info["build_cmd"]
        ))

    # Lint stage — informational only, never blocks or triggers auto-fix
    if "lint" not in skip_stages:
        if _lint_tool:
            stages.append(("Lint", "lint_info", (_lint_tool, "")))
        elif project_info.get("lint_cmd") and project_info.get(
            "type"
        ) in ("rust", "go"):
            stages.append((
                "Lint", "lint_info", project_info["lint_cmd"]
            ))

    # Test stage — prefer tool_run_tests (auto-detects runner), fall back
    if "test" not in skip_stages and "tests" not in skip_stages:
        test_dirs = (
            "tests", "test", "src/tests", "spec", "__tests__",
        )
        if any((base_dir / d).exists() for d in test_dirs):
            if _test_tool:
                stages.append(("Tests", "tool_func", (_test_tool, "")))
            elif project_info.get("test_cmd"):
                stages.append((
                    "Tests", "command", project_info["test_cmd"]
                ))

    # Append custom validation stages from plan
    for cs in custom_stages:
        if isinstance(cs, dict) and "name" in cs and "command" in cs:
            stages.append((
                cs["name"], "command", cs["command"]
            ))

    if not stages:
        console.print(
            "[dim]No validation stages applicable.[/dim]"
        )
        return True

    console.print(Panel.fit(
        f"[bold]🧪 Validation Pipeline"
        f"{f' — {step_label}' if step_label else ''}"
        f"[/bold]\n"
        + "\n".join(
            f"  {i + 1}. {name}"
            for i, (name, _, _) in enumerate(stages)
        ),
        border_style="yellow",
    ))

    for stage_name, stage_type, stage_cmd in stages:
        console.print(
            f"\n[bold cyan]▶ {stage_name}...[/bold cyan]"
        )

        passed = False
        _seen_error_hashes: set[str] = set()
        _last_error_hash: str = ""
        stage_fix_history: list[FixAttempt] = []
        for attempt in range(MAX_FIX_ATTEMPTS):
            if stage_type == "xref":
                passed = _validate_xref(
                    base_dir, plan, created_files,
                    config, stage_name, attempt,
                    fix_history=stage_fix_history,
                )
            elif stage_type == "syntax_check":
                passed = _validate_syntax(
                    base_dir, plan, created_files,
                    config, stage_name, attempt,
                    fix_history=stage_fix_history,
                )
            elif stage_type == "dep_validate":
                passed = _validate_dependencies(
                    base_dir, stage_cmd,
                )
            elif stage_type == "command":
                passed = _validate_command(
                    stage_cmd, base_dir, plan,
                    created_files, config,
                    stage_name, attempt,
                    fix_history=stage_fix_history,
                )
            elif stage_type == "lint_info":
                passed = _run_lint_info(
                    stage_cmd, base_dir, stage_name,
                )
            elif stage_type == "tool_func":
                tfunc, targs = stage_cmd  # unpacked from tuple
                passed = _validate_tool_func(
                    tfunc, targs, base_dir, plan,
                    created_files, config,
                    stage_name, attempt,
                    fix_history=stage_fix_history,
                )

            if passed:
                break

            # Detect duplicate errors — bail early if stuck in a loop.
            # Re-run the command/tool to capture its current output for hashing.
            if stage_type == "command" and stage_cmd:
                probe = run_cmd(stage_cmd, cwd=str(base_dir))
                sig_data = (probe.get("stdout", "") + probe.get("stderr", "")).strip()
            elif stage_type == "tool_func":
                tfunc, targs = stage_cmd
                original_dir = os.getcwd()
                try:
                    os.chdir(str(base_dir))
                    sig_data = tfunc(targs)
                except Exception:
                    sig_data = f"{stage_name}:tool_func:error"
                finally:
                    os.chdir(original_dir)
            else:
                sig_data = f"{stage_name}:{stage_type}:{passed}"
            error_hash = hashlib.md5(sig_data.encode()).hexdigest()
            if error_hash in _seen_error_hashes:
                console.print(
                    "[yellow]Same error repeated — skipping "
                    "remaining fix attempts[/yellow]"
                )
                break
            _seen_error_hashes.add(error_hash)
            _last_error_hash = error_hash

        if not passed:
            if not handle_validation_failure(stage_name):
                return False

    console.print(
        "\n[bold green]✅ All validation passed![/bold green]"
    )
    return True


def _run_lint_info(stage_cmd, base_dir: Path, stage_name: str) -> bool:
    """Run lint as informational-only — never blocks, never auto-fixes."""
    if isinstance(stage_cmd, tuple):
        # tool_func: (func, args)
        tool_func, tool_args = stage_cmd
        original_dir = os.getcwd()
        try:
            os.chdir(str(base_dir))
            result_text = tool_func(tool_args)
        except Exception as e:
            console.print(f"  [dim]Lint skipped: {e}[/dim]")
            return True
        finally:
            os.chdir(original_dir)
    else:
        # command string
        result = run_cmd(stage_cmd, cwd=str(base_dir))
        result_text = (result.get("stdout", "") + "\n" + result.get("stderr", "")).strip()
        if result["success"]:
            result_text = f"[lint] clean (exit 0)\n{result_text}"

    lines = result_text.strip().split("\n")
    first_line = lines[0] if lines else ""

    if _parse_tool_result(result_text):
        console.print(f"  [green]\u2713 {stage_name} clean[/green]")
    elif "not found" in first_line.lower() or "not installed" in first_line.lower():
        console.print(f"  [dim]{stage_name} skipped (tool not available)[/dim]")
    else:
        console.print(f"  [yellow]\u2139 {stage_name}: {first_line}[/yellow]")
        for line in lines[1:6]:
            console.print(f"    [dim]{line}[/dim]")
    return True  # Never block


def _validate_xref(
    base_dir, plan, created_files, config,
    stage_name, attempt,
    fix_history: list[FixAttempt] | None = None,
) -> bool:
    try:
        ctx = scan_project(base_dir, auto_detect=False)
    except Exception as e:
        console.print(
            f"  [yellow]⚠ Scan error: {e}[/yellow]"
        )
        return True

    errors = [
        i for i in ctx.issues
        if i.get("severity") == "error"
    ]
    warnings = [
        i for i in ctx.issues
        if i.get("severity") == "warning"
    ]

    if not errors:
        console.print(
            "  [green]✓ No broken references[/green]"
        )
        if warnings:
            console.print(
                f"  [yellow]  ({len(warnings)} "
                f"warnings)[/yellow]"
            )
        return True

    console.print(
        f"  [red]✗ {len(errors)} broken "
        f"reference(s)[/red]"
    )
    for err in errors[:10]:
        console.print(
            f"    [red]• {err.get('message', '')}[/red]"
        )

    if attempt < MAX_FIX_ATTEMPTS - 1:
        console.print(
            f"\n[yellow]🔧 Auto-fix attempt "
            f"{attempt + 1}/{MAX_FIX_ATTEMPTS}...[/yellow]"
        )
        error_msg = "\n".join(
            e.get("message", "") for e in errors
        )
        error_info = {
            "command": "cross-reference validation",
            "returncode": 1,
            "stdout": "",
            "stderr": (
                f"Broken references:\n{error_msg}"
            ),
        }
        created_files.update(build_file_map(ctx))
        auto_fix(
            error_info, base_dir, plan, created_files,
            config, attempt=attempt,
            fix_history=fix_history,
        )

    return False


def _validate_syntax(
    base_dir, plan, created_files, config,
    stage_name, attempt,
    fix_history: list[FixAttempt] | None = None,
) -> bool:
    try:
        ctx = scan_project(base_dir, auto_detect=False)
    except Exception as e:
        console.print(
            f"  [yellow]⚠ Scan error: {e}[/yellow]"
        )
        return True

    syntax_errors = []
    for fpath, info in ctx.files.items():
        if hasattr(info, 'errors') and info.errors:
            syntax_errors.extend(
                (fpath, err) for err in info.errors
            )

    if not syntax_errors:
        console.print(
            "  [green]✓ All files parse correctly[/green]"
        )
        return True

    console.print(
        f"  [red]✗ {len(syntax_errors)} syntax "
        f"error(s)[/red]"
    )
    for fpath, err in syntax_errors[:10]:
        console.print(f"    [red]• {fpath}: {err}[/red]")

    if attempt < MAX_FIX_ATTEMPTS - 1:
        console.print(
            f"\n[yellow]🔧 Auto-fix attempt "
            f"{attempt + 1}/{MAX_FIX_ATTEMPTS}...[/yellow]"
        )
        error_msg = "\n".join(
            f"{f}: {e}" for f, e in syntax_errors
        )
        error_info = {
            "command": "syntax check",
            "returncode": 1,
            "stdout": "",
            "stderr": f"Syntax errors:\n{error_msg}",
        }
        created_files.update(build_file_map(ctx))
        auto_fix(
            error_info, base_dir, plan, created_files,
            config, attempt=attempt,
            fix_history=fix_history,
        )

    return False


def _validate_command(
    stage_cmd, base_dir, plan, created_files, config,
    stage_name, attempt,
    fix_history: list[FixAttempt] | None = None,
) -> bool:
    """Run a command-based validation stage with smart error diagnosis."""
    result = run_cmd(stage_cmd, cwd=str(base_dir))

    if result["success"]:
        console.print(
            f"  [green]✓ {stage_name} passed[/green]"
        )
        if result["stdout"]:
            for line in (
                result["stdout"].strip().split("\n")[-5:]
            ):
                console.print(f"  [dim]{line}[/dim]")
        return True

    console.print(
        f"  [red]✗ {stage_name} failed "
        f"(exit {result['returncode']})[/red]"
    )

    # ── Show error output ──────────────────────────────
    stderr_text = result.get("stderr", "")
    stdout_text = result.get("stdout", "")

    output_to_show = stderr_text or stdout_text
    if output_to_show:
        console.print(Panel(output_to_show[:1500], title="Error", border_style="red"))

    # ── Diagnose the error ─────────────────────────────
    combined = f"{stdout_text}\n{stderr_text}"
    diagnosis = diagnose_test_error(combined)

    if diagnosis["error_type"] != "unknown":
        console.print(
            f"  [cyan]📋 Diagnosis: {diagnosis['error_type']}[/cyan]"
        )
        if diagnosis["missing_module"]:
            console.print(
                f"  [cyan]   Module: {diagnosis['missing_module']}[/cyan]"
            )
        if diagnosis["is_local_import"]:
            console.print(
                "  [yellow]   ⚠ LOCAL module — will fix import path, "
                "NOT requirements.txt[/yellow]"
            )
        elif diagnosis["is_pip_package"]:
            console.print(
                "  [cyan]   📦 Missing pip package — will update "
                "requirements.txt[/cyan]"
            )
        if diagnosis["affected_files"]:
            for af in diagnosis["affected_files"][:3]:
                console.print(f"  [dim]   → {af}[/dim]")

    if attempt < MAX_FIX_ATTEMPTS - 1:
        # ── Try reinstalling deps ONLY if it's actually a dep issue ──
        is_dep_error = _is_missing_dependency_error(
            result.get("stderr", ""),
            result.get("stdout", ""),
        )

        # But NOT if our diagnosis says it's a local import
        if is_dep_error and not diagnosis.get("is_local_import", False):
            reinstalled = _try_reinstall_deps(
                base_dir, plan
            )
            if reinstalled:
                retry_result = run_cmd(
                    stage_cmd, cwd=str(base_dir)
                )
                if retry_result["success"]:
                    console.print(
                        f"  [green]✓ {stage_name} passed "
                        f"after reinstall[/green]"
                    )
                    if retry_result["stdout"]:
                        for line in (
                            retry_result["stdout"]
                            .strip()
                            .split("\n")[-5:]
                        ):
                            console.print(
                                f"  [dim]{line}[/dim]"
                            )
                    return True
                console.print(
                    "  [yellow]Still failing after "
                    "reinstall — asking LLM...[/yellow]"
                )
        elif is_dep_error and diagnosis.get("is_local_import", False):
            console.print(
                "  [yellow]Skipping dependency reinstall — "
                "this is a local import issue[/yellow]"
            )

        console.print(
            f"\n[yellow]🔧 Auto-fix attempt "
            f"{attempt + 1}/{MAX_FIX_ATTEMPTS}...[/yellow]"
        )
        try:
            created_files.update(
                build_file_map(scan_project(base_dir, auto_detect=False))
            )
        except Exception:
            pass

        # Snapshot files before fix for potential rollback
        snapshot = FileSnapshot()
        all_project_files = list(created_files.keys())
        snapshot.snapshot_files(all_project_files[:50], base_dir)

        fixed = auto_fix(
            result, base_dir, plan, created_files,
            config, attempt=attempt,
            fix_history=fix_history,
        )

        # Record this fix attempt in history
        if fix_history is not None:
            modified = snapshot.get_modified_files()
            error_summary = (
                result.get("stderr", "") or result.get("stdout", "")
            )[:300]
            fix_history.append(FixAttempt(
                attempt=attempt + 1,
                error_summary=error_summary,
                files_modified=modified,
                approach=f"auto_fix attempt {attempt + 1}",
                result="applied" if fixed else "no_change",
            ))

        if not fixed:
            # Rollback failed fix if nothing was written
            snapshot.rollback()
            console.print(
                "[red]No fixes generated.[/red]"
            )
            if not ask_continue():
                return False

    return False


# ── Pre-Step Validation ────────────────────────────────────────

def pre_step_validation(
    base_dir: Path,
    plan: dict,
    created_files: dict[str, str],
    config: dict,
) -> bool:
    """Validate project state before starting the next step.

    Checks for syntax errors and broken imports left by
    previous steps. If issues are found, attempts auto_fix
    before proceeding.

    Returns:
        True if project is in a healthy state (or was healed).
    """
    try:
        ctx = scan_project(base_dir, auto_detect=False)
    except Exception as e:
        console.print(
            f"  [yellow]⚠ Pre-step scan error: {e}[/yellow]"
        )
        return True  # Don't block on scan failure

    # Check for syntax errors
    syntax_errors = []
    for fpath, info in ctx.files.items():
        if hasattr(info, "errors") and info.errors:
            syntax_errors.extend(
                (fpath, err) for err in info.errors
            )

    # Check for severity=error import issues
    import_errors = [
        i for i in ctx.issues
        if i.get("severity") == "error"
        and i.get("type") == "missing_import"
    ]

    if not syntax_errors and not import_errors:
        return True

    issue_count = len(syntax_errors) + len(import_errors)
    console.print(
        f"\n[yellow]⚠ Pre-step check: "
        f"{issue_count} issue(s) from prior steps[/yellow]"
    )
    for fpath, err in syntax_errors[:5]:
        console.print(f"  [red]• {fpath}: {err}[/red]")
    for err in import_errors[:5]:
        console.print(
            f"  [red]• {err.get('message', '')}[/red]"
        )

    # Attempt auto-fix
    console.print(
        "[yellow]🔧 Attempting to heal before "
        "next step...[/yellow]"
    )
    error_msgs = []
    error_msgs.extend(
        f"Syntax: {f}: {e}" for f, e in syntax_errors
    )
    error_msgs.extend(
        e.get("message", "") for e in import_errors
    )
    error_info = {
        "command": "pre-step validation",
        "returncode": 1,
        "stdout": "",
        "stderr": "\n".join(error_msgs),
    }
    created_files.update(build_file_map(ctx))
    fixed = auto_fix(
        error_info, base_dir, plan, created_files,
        config, attempt=0,
    )

    if fixed:
        # Re-check after fix
        try:
            ctx2 = scan_project(base_dir, auto_detect=False)
            remaining_errors = [
                i for i in ctx2.issues
                if i.get("severity") == "error"
            ]
            remaining_syntax = sum(
                1 for info in ctx2.files.values()
                if hasattr(info, "errors") and info.errors
            )
            if not remaining_errors and not remaining_syntax:
                console.print(
                    "  [green]✓ Pre-step issues "
                    "resolved[/green]"
                )
                return True
        except Exception:
            pass

    console.print(
        "  [yellow]⚠ Some pre-step issues remain — "
        "proceeding anyway[/yellow]"
    )
    return True  # Don't block the build
